# Generated by Django 3.1.2 on 2020-11-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201118_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fullname',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
