# Generated by Django 3.1.2 on 2020-11-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_emailsendcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsendcount',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
